---
- hosts: all

  tasks:
#  - name:  Copy a file
#    copy:
#      src: demo_files/fileA.txt
#      dest: /opt/dest/team.txt
#      owner: root
#      group: root
#      mode: 0744
#      backup: yes`

  - name: Copy multiple files
    copy:
      src: "{{ item }}"
      dest: /opt/dest/
      owner: root
      group: root
      mode: 0744
      backup: yes
    with_items:
      - "demo_files/fileA.txt"
      - "demo_files/fileB.txt"
