---
- hosts: all

  tasks:
#  - name:  Copy a file
#    copy:
#      src: demo_files/fileA.txt
#      dest: /opt/dest/team.txt
#      owner: root
#      group: root
#      mode: 0744
#      backup: yes`

  - name: Copy multiple files, different owners,permissions, and destination
    copy:
      src: "{{ item.srcPath }}"
      dest: "{{ item.destPath }}"
      owner: "{{ item.owner }}"
      group: root
      mode: "{{ item.mode }}"
      backup: yes
    with_items:
      - { srcPath: 'demo_files/fileA.txt', destPath: '/opt/dest/teamA.txt' , owner: 'root' ,mode: '0644' }
      - { srcPath: 'demo_files/fileB.txt', destPath: '/opt/dest/teamB.txt' , owner: 'centos' ,mode: '0755' }
