---
- hosts: all

  tasks:
    - name: Checking ssh access
      ping:

    - name: Gather local disk usage info
      shell: "df -hl"
      register: localFS

    - debug:
        var: localFS
        verbosity: 1

    - debug:
        msg:
          - "Local filesystem info"
          - "{{ localFS.stdout_lines }}"
