---
- hosts: all

  tasks:
  - name: Deploy team template file
    template:
      src: demo_files/team.j2
      dest: /opt/dest/teamColor.txt
      owner: root
      group: root
      mode: '0644'
      backup: yes
